typography_spectrum: 0.35034
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6060694183688611
  lightness: 0.3504122586455196
  saturation: 0.9297944761347026
  rhythmicContrast: 0.287829112727195
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25149
analytics:
  google: null
  facebook: null
  twitter: null
name: StavrosPavlides
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Stavros Pavlides Art
description: Always be better
purpose: []
